---
deployment:
  tasks:
    - export DEPLOYPATH=/home/samlbdzy/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp contact.html $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH/css
    - /bin/cp -R posts $DEPLOYPATH/posts/
    - /bin/cp -R js $DEPLOYPATH/js/
    - /bin/cp -R images $DEPLOYPATH/images/
