---
deployment:
  tasks:
    - export DEPLOYPATH=/home/samlbdzy/public_html/
    - /bin/rsync -av --delete \
      --no-perms --no-owner --no-group \
      --chmod=Du=rwx,Dgo=rx,Fu=rw,Fgo=r \
      --exclude='.git/' \
      ./ $DEPLOYPATH
